version: "3"
services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro

  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URL=mongodb://mongodb:27017/taskScheduler
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_WEBSOCKET_URL=ws://localhost:8080
      - REACT_APP_API_URL=http://localhost:3001/api
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
